import { createSlice } from "@reduxjs/toolkit";

const initialState = {
    products:['Balozi', 'Balozi can',
        'White cap',
        'White cap can',
        'Tusker',
        'Tusker can',
        'Tusker cider',
        'Cider can',
        'Tusker Lite',
        'Tusker Lite Can',
        'Tusker malt',
        'Pilsner',
        'Guiness',
        'Guiness Can',
        'Guiness smooth',
        'Summit',
        'K.B',
        'Snapp',
        'Caprice',
        'Faxe',
        'Guaranna',
        'Red Bull',
        'Monster',
        'Richot 750ml',
        'richot 1/2',
        'Richot 1/4',
        'KC',
        'KC1/2',
        'KC1/4',
        'Smirnoff vodka',
        'Smirnoff vodka1/2',
        'Smirnoff vodka1/4',
        'Black ice',
        'V&A',
        'Viceroy',
        'Viceroy1/2',
        'Viceroy1/4',
        'Gilbeys',
        'Gilbeys1/2',
        'Gilbeys1/4',
        'Captain',
        'captain1/4',
        'Famous Grouse',
        'Black &White',
        'Black&White1/2', 
        'Royal Stag',
        'Kibao',
        'Kibao1/2',
        'Kibao1/4',
        'All seasons',
        'All seasons1/2',
        'All seasons1/4',
        'VAT69',
        'VAT691/2',
        'Imperial',
        'Hunters',
        'Hunters1/2',
        'Hunters1/4',
        'Konyagi',
        'Konyagi1/2',
        'Konyagi1/4',
        'Chrome vodka',
        'Chrome GIN 1/4',
        'Chrome vodka 1/4',
        'Bond',
        'T.Ace1/2',
        'T.Ace1/4',
        'Cellar cask',
        '4th Street',
        'Soda 500 ml',
        'Soda 300 ml',
        'Soda water',
        'Predator',
        'Delmonte',
        'King Fisher',
        'Red Label',
        'H20 LTR',
        'H20 500ml',
        'Lemonade'],
    isLoading:false,
}
const productsSlice = createSlice({
    name:'All products',
    initialState,
    reducers:{
        addproduct:(state , action)=>{
            state.products.push(action.payload);
    }

    }

});
export default productsSlice.reducer;